/*
 * XingChen 开放接口定义
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alibaba.xingchen.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.util.Objects;

/**
 * CharacterKey
 */
@Data
@SuperBuilder
@NoArgsConstructor
public class CharacterKey {
  // 星尘创建的角色ID
  private String characterId;

  // 角色版本
  private Integer version;

  // 角色自定义
  // 角色名称
  private String name;

  // 角色配置
  private String content;

  public boolean validate() {
    return Objects.nonNull(characterId) || Objects.nonNull(content);
  }
}

