/*
 * XingChen 开放接口定义
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alibaba.xingchen.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.util.Date;
import java.util.List;

/**
 * 角色信息
 */
@Data
@SuperBuilder
@NoArgsConstructor
public class CharacterDTO {
  private String name;

  private FileInfoVO avatar;

  private String introduction;

  private String basicInformation;

  private String openingLine;

  private String traits;

  private String chatExample;

  private String type;

  private String chatObjective;

  private CharacterAdvancedConfig advancedConfig;

  private String characterId;

  private Integer version;

  private Integer majorVersion;

  private Long gmtCreate;

  private Long gmtModified;

  private String userId;

  private String modifiedBy;

  private List<String> tags = null;

  private String backgroundImgUrl;

  private CharacterPermissionConfig permConfig;

  private List<Integer> versions = null;

  private Boolean manageable;

  private String creator;

  private Boolean isPreConfigured;
}

