/*
 * XingChen 开放接口定义
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alibaba.xingchen.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.util.List;

/**
 * 查询条件
 */
@Data
@SuperBuilder
@NoArgsConstructor
public class ChatHistoryQueryWhere {
  /**
   * 角色ID
   */
  private String characterId;
  /**
   * 对话用户ID
   */
  private String bizUserId;
  /**
   * 对话ID
   */
  private String sessionId;

  /**
   * 开始时间
   */
  private Long startTime;
  /**
   * 结束时间
   */
  private Long endTime;
  /**
   * 消息ID列表
   */
  private List<String> messageIds = null;
}

