/*
 * XingChen 开放接口定义
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alibaba.xingchen.model;

import lombok.Data;

/**
 * 聊天消息
 */
@Data
public class ChatMessageDTO {
  private String content;

  private String messageType;

  private String messageId;

  private ChatRoomUserDTO messageIssuer;

  private String sessionId;
  private String chatId;

  private Long gmtCreate;

  private Boolean isGreeting;

  private Double rating;

  private Integer regenerateTimes;
}

