/*
 * XingChen 开放接口定义
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alibaba.xingchen.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * ModelParameters
 */
@Data
@NoArgsConstructor
@SuperBuilder
public class ModelParameters {
  private String modelName;

  private Double topP;

  private Integer topK;

  private Long seed;

  /**
   * 模型生成最大token数
   */
  private Integer maxLength;

  /**
   * 模型生成最小token数
   */
  private Integer minLength;

  /**
   * 较高的值将使输出更加随机，而较低的值将使输出更加集中和确定。可选，默认取值0.8
   */
  private Double temperature;
}

