/*
 * XingChen 开放接口定义
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alibaba.xingchen;

import com.google.gson.*;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gsonfire.GsonFireBuilder;
import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Map;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    {
        GsonBuilder gsonBuilder = createGson();
//        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
//        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
//        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.AdvancedSettings.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.CharacterAdvancedConfig.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.CharacterCreateDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.CharacterDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.CharacterKey.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.CharacterPermissionConfig.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.CharacterQueryDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.CharacterQueryWhere.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.CharacterUpdateDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.CharacterVersionCreateOrUpdateDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ChatHistoryQueryDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ChatHistoryQueryWhere.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ChatMessageDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ChatReqParams.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ChatResult.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ChatRoomUserDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.Choice.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.Context.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.FileInfoVO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.Message.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.MessageRatingRequest.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.Meta.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ModelParameters.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.PageResultCharacterDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.PageResultChatMessageDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.Repository.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.RepositoryInfo.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ResultDTOBoolean.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ResultDTOCharacterDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ResultDTOCharacterKey.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ResultDTOChatResult.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ResultDTOListCharacterDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ResultDTOPageResultCharacterDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.ResultDTOPageResultChatMessageDTO.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.Scenario.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.SysReminderRequest.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.Usage.CustomTypeAdapterFactory());
//        gsonBuilder.registerTypeAdapterFactory(new com.alibaba.xingchen.model.UserProfile.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateTimeFormatter dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateTimeFormatter dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                LocalDateTime localDateTime = LocalDateTime.ofEpochSecond(Long.valueOf(date)/1000L, 0, ZoneOffset.ofHours(8));
                                return Date.from(localDateTime.toInstant(ZoneOffset.ofHours(8)));
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateTimeFormatter(DateTimeFormatter dateTimeFormatter) {
        dateTypeAdapter.setFormat(dateTimeFormatter);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
